version: '3.9'
services:
  rest:
    build:
      context: .
      dockerfile: docker/rest/Dockerfile
    container_name: yd-rest
    ports:
      - '8081:8081'
    environment:
      MODE: "DOCKER"
    depends_on:
      - storage
      - downloader

  storage:
    build:
      context: .
      dockerfile: docker/storage/Dockerfile
    container_name: yd-storage
    ports:
      - '50051:50051'
    environment:
      MODE: "DOCKER"
    depends_on:
      - downloader

  downloader:
    build:
      context: .
      dockerfile: docker/downloader/Dockerfile
    container_name: yd-downloader
    ports:
      - '50052:50052'
    environment:
      MODE: "DOCKER"
    depends_on:
      kafka:
        condition: service_healthy


  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - 'minio_data:/data'

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9093:9093"
    expose:
      - "9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "download-task:1:1,download-done:1:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    healthcheck:
      test:
        [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "kafka:9093"]
      interval: 10s
      timeout: 30s
      retries: 4
    depends_on:
      - zookeeper

volumes:
  minio_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
